// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MtfsService_Serve_FullMethodName = "/mtfs.MtfsService/Serve"
)

// MtfsServiceClient is the client API for MtfsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MtfsServiceClient interface {
	// Creates a working connection to the MTFS service.
	Serve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OperationRequest, OperationResponse], error)
}

type mtfsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMtfsServiceClient(cc grpc.ClientConnInterface) MtfsServiceClient {
	return &mtfsServiceClient{cc}
}

func (c *mtfsServiceClient) Serve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OperationRequest, OperationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MtfsService_ServiceDesc.Streams[0], MtfsService_Serve_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OperationRequest, OperationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtfsService_ServeClient = grpc.BidiStreamingClient[OperationRequest, OperationResponse]

// MtfsServiceServer is the server API for MtfsService service.
// All implementations must embed UnimplementedMtfsServiceServer
// for forward compatibility.
type MtfsServiceServer interface {
	// Creates a working connection to the MTFS service.
	Serve(grpc.BidiStreamingServer[OperationRequest, OperationResponse]) error
	mustEmbedUnimplementedMtfsServiceServer()
}

// UnimplementedMtfsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMtfsServiceServer struct{}

func (UnimplementedMtfsServiceServer) Serve(grpc.BidiStreamingServer[OperationRequest, OperationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Serve not implemented")
}
func (UnimplementedMtfsServiceServer) mustEmbedUnimplementedMtfsServiceServer() {}
func (UnimplementedMtfsServiceServer) testEmbeddedByValue()                     {}

// UnsafeMtfsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MtfsServiceServer will
// result in compilation errors.
type UnsafeMtfsServiceServer interface {
	mustEmbedUnimplementedMtfsServiceServer()
}

func RegisterMtfsServiceServer(s grpc.ServiceRegistrar, srv MtfsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMtfsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MtfsService_ServiceDesc, srv)
}

func _MtfsService_Serve_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MtfsServiceServer).Serve(&grpc.GenericServerStream[OperationRequest, OperationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MtfsService_ServeServer = grpc.BidiStreamingServer[OperationRequest, OperationResponse]

// MtfsService_ServiceDesc is the grpc.ServiceDesc for MtfsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MtfsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mtfs.MtfsService",
	HandlerType: (*MtfsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Serve",
			Handler:       _MtfsService_Serve_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
