// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimStatus int32

const (
	ClaimStatus_CLAIM_STATUS_UNSPECIFIED             ClaimStatus = 0 // Unspecified claim status
	ClaimStatus_CLAIM_STATUS_EXCLUSIVE_WRITE_GRANTED ClaimStatus = 1 // Exclusive write access granted
	ClaimStatus_CLAIM_STATUS_LOCK_READ_GRANTED       ClaimStatus = 2 // Read lock granted
	ClaimStatus_CLAIM_STATUS_EXCLUSIVE_WRITE_REVOKED ClaimStatus = 3 // Write lock revoked
	ClaimStatus_CLAIM_STATUS_LOCK_READ_REVOKED       ClaimStatus = 4 // Read lock revoked
)

// Enum value maps for ClaimStatus.
var (
	ClaimStatus_name = map[int32]string{
		0: "CLAIM_STATUS_UNSPECIFIED",
		1: "CLAIM_STATUS_EXCLUSIVE_WRITE_GRANTED",
		2: "CLAIM_STATUS_LOCK_READ_GRANTED",
		3: "CLAIM_STATUS_EXCLUSIVE_WRITE_REVOKED",
		4: "CLAIM_STATUS_LOCK_READ_REVOKED",
	}
	ClaimStatus_value = map[string]int32{
		"CLAIM_STATUS_UNSPECIFIED":             0,
		"CLAIM_STATUS_EXCLUSIVE_WRITE_GRANTED": 1,
		"CLAIM_STATUS_LOCK_READ_GRANTED":       2,
		"CLAIM_STATUS_EXCLUSIVE_WRITE_REVOKED": 3,
		"CLAIM_STATUS_LOCK_READ_REVOKED":       4,
	}
)

func (x ClaimStatus) Enum() *ClaimStatus {
	p := new(ClaimStatus)
	*p = x
	return p
}

func (x ClaimStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ClaimStatus) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ClaimStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimStatus.Descriptor instead.
func (ClaimStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type OperationRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Cookie []byte                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`             // Cookie for the request
	SeqId  int64                  `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"` // Sequence ID of the request
	// Types that are valid to be assigned to Operation:
	//
	//	*OperationRequest_Mkdir
	//	*OperationRequest_Lookup
	//	*OperationRequest_GetAttr
	//	*OperationRequest_Mknod
	//	*OperationRequest_Rmdir
	//	*OperationRequest_Unlink
	//	*OperationRequest_Symlink
	//	*OperationRequest_Readlink
	//	*OperationRequest_SetAttr
	//	*OperationRequest_ScanDir
	Operation     isOperationRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *OperationRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *OperationRequest) GetOperation() isOperationRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *OperationRequest) GetMkdir() *MkdirRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *OperationRequest) GetLookup() *LookupRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

func (x *OperationRequest) GetGetAttr() *GetAttrRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_GetAttr); ok {
			return x.GetAttr
		}
	}
	return nil
}

func (x *OperationRequest) GetMknod() *MknodRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Mknod); ok {
			return x.Mknod
		}
	}
	return nil
}

func (x *OperationRequest) GetRmdir() *RmdirRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Rmdir); ok {
			return x.Rmdir
		}
	}
	return nil
}

func (x *OperationRequest) GetUnlink() *UnlinkRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Unlink); ok {
			return x.Unlink
		}
	}
	return nil
}

func (x *OperationRequest) GetSymlink() *SymlinkRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Symlink); ok {
			return x.Symlink
		}
	}
	return nil
}

func (x *OperationRequest) GetReadlink() *ReadlinkRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Readlink); ok {
			return x.Readlink
		}
	}
	return nil
}

func (x *OperationRequest) GetSetAttr() *SetAttrRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_SetAttr); ok {
			return x.SetAttr
		}
	}
	return nil
}

func (x *OperationRequest) GetScanDir() *ScanDirectoryRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_ScanDir); ok {
			return x.ScanDir
		}
	}
	return nil
}

type isOperationRequest_Operation interface {
	isOperationRequest_Operation()
}

type OperationRequest_Mkdir struct {
	// Request to create a directory.
	Mkdir *MkdirRequest `protobuf:"bytes,3,opt,name=mkdir,proto3,oneof"`
}

type OperationRequest_Lookup struct {
	Lookup *LookupRequest `protobuf:"bytes,4,opt,name=lookup,proto3,oneof"` // Request to look up a file or directory
}

type OperationRequest_GetAttr struct {
	GetAttr *GetAttrRequest `protobuf:"bytes,5,opt,name=get_attr,json=getAttr,proto3,oneof"` // Request to get file or directory attributes
}

type OperationRequest_Mknod struct {
	Mknod *MknodRequest `protobuf:"bytes,6,opt,name=mknod,proto3,oneof"` // Request to create a node (file, symlink, etc.)
}

type OperationRequest_Rmdir struct {
	Rmdir *RmdirRequest `protobuf:"bytes,7,opt,name=rmdir,proto3,oneof"` // Request to remove a directory
}

type OperationRequest_Unlink struct {
	Unlink *UnlinkRequest `protobuf:"bytes,8,opt,name=unlink,proto3,oneof"` // Request to remove a file
}

type OperationRequest_Symlink struct {
	Symlink *SymlinkRequest `protobuf:"bytes,9,opt,name=symlink,proto3,oneof"` // Request to create a symlink
}

type OperationRequest_Readlink struct {
	Readlink *ReadlinkRequest `protobuf:"bytes,10,opt,name=readlink,proto3,oneof"` // Request to read a symlink
}

type OperationRequest_SetAttr struct {
	SetAttr *SetAttrRequest `protobuf:"bytes,11,opt,name=set_attr,json=setAttr,proto3,oneof"` // Request to set attributes of a file or directory
}

type OperationRequest_ScanDir struct {
	ScanDir *ScanDirectoryRequest `protobuf:"bytes,12,opt,name=scan_dir,json=scanDir,proto3,oneof"`
}

func (*OperationRequest_Mkdir) isOperationRequest_Operation() {}

func (*OperationRequest_Lookup) isOperationRequest_Operation() {}

func (*OperationRequest_GetAttr) isOperationRequest_Operation() {}

func (*OperationRequest_Mknod) isOperationRequest_Operation() {}

func (*OperationRequest_Rmdir) isOperationRequest_Operation() {}

func (*OperationRequest_Unlink) isOperationRequest_Operation() {}

func (*OperationRequest_Symlink) isOperationRequest_Operation() {}

func (*OperationRequest_Readlink) isOperationRequest_Operation() {}

func (*OperationRequest_SetAttr) isOperationRequest_Operation() {}

func (*OperationRequest_ScanDir) isOperationRequest_Operation() {}

type OperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence ID of the request, 0 if it's notification from the server
	SeqId  int64  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Cookie []byte `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"` // Cookie for the identity of the inode.
	// Types that are valid to be assigned to Response:
	//
	//	*OperationResponse_ClaimUpdate
	//	*OperationResponse_Mkdir
	//	*OperationResponse_Lookup
	//	*OperationResponse_GetAttr
	//	*OperationResponse_Mknod
	//	*OperationResponse_Rmdir
	//	*OperationResponse_Unlink
	//	*OperationResponse_Symlink
	//	*OperationResponse_Readlink
	//	*OperationResponse_SetAttr
	//	*OperationResponse_ScanDir
	Response      isOperationResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *OperationResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *OperationResponse) GetResponse() isOperationResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OperationResponse) GetClaimUpdate() *ClaimUpdateServerRequest {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_ClaimUpdate); ok {
			return x.ClaimUpdate
		}
	}
	return nil
}

func (x *OperationResponse) GetMkdir() *MkdirResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *OperationResponse) GetLookup() *LookupResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

func (x *OperationResponse) GetGetAttr() *GetAttrResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_GetAttr); ok {
			return x.GetAttr
		}
	}
	return nil
}

func (x *OperationResponse) GetMknod() *MknodResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Mknod); ok {
			return x.Mknod
		}
	}
	return nil
}

func (x *OperationResponse) GetRmdir() *RmdirResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Rmdir); ok {
			return x.Rmdir
		}
	}
	return nil
}

func (x *OperationResponse) GetUnlink() *UnlinkResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Unlink); ok {
			return x.Unlink
		}
	}
	return nil
}

func (x *OperationResponse) GetSymlink() *SymlinkResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Symlink); ok {
			return x.Symlink
		}
	}
	return nil
}

func (x *OperationResponse) GetReadlink() *ReadlinkResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Readlink); ok {
			return x.Readlink
		}
	}
	return nil
}

func (x *OperationResponse) GetSetAttr() *SetAttrResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_SetAttr); ok {
			return x.SetAttr
		}
	}
	return nil
}

func (x *OperationResponse) GetScanDir() *ScanDirectoryResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_ScanDir); ok {
			return x.ScanDir
		}
	}
	return nil
}

type isOperationResponse_Response interface {
	isOperationResponse_Response()
}

type OperationResponse_ClaimUpdate struct {
	// Notifications from the server.
	ClaimUpdate *ClaimUpdateServerRequest `protobuf:"bytes,6,opt,name=claim_update,json=claimUpdate,proto3,oneof"` // Claim update request
}

type OperationResponse_Mkdir struct {
	Mkdir *MkdirResponse `protobuf:"bytes,3,opt,name=mkdir,proto3,oneof"`
}

type OperationResponse_Lookup struct {
	Lookup *LookupResponse `protobuf:"bytes,4,opt,name=lookup,proto3,oneof"`
}

type OperationResponse_GetAttr struct {
	GetAttr *GetAttrResponse `protobuf:"bytes,5,opt,name=get_attr,json=getAttr,proto3,oneof"`
}

type OperationResponse_Mknod struct {
	Mknod *MknodResponse `protobuf:"bytes,7,opt,name=mknod,proto3,oneof"`
}

type OperationResponse_Rmdir struct {
	Rmdir *RmdirResponse `protobuf:"bytes,8,opt,name=rmdir,proto3,oneof"` // Response to remove a directory
}

type OperationResponse_Unlink struct {
	Unlink *UnlinkResponse `protobuf:"bytes,9,opt,name=unlink,proto3,oneof"` // Response to remove a file
}

type OperationResponse_Symlink struct {
	Symlink *SymlinkResponse `protobuf:"bytes,10,opt,name=symlink,proto3,oneof"` // Response to create a symlink
}

type OperationResponse_Readlink struct {
	Readlink *ReadlinkResponse `protobuf:"bytes,11,opt,name=readlink,proto3,oneof"` // Response to read a symlink
}

type OperationResponse_SetAttr struct {
	SetAttr *SetAttrResponse `protobuf:"bytes,12,opt,name=set_attr,json=setAttr,proto3,oneof"` // Response to set attributes of a file or directory
}

type OperationResponse_ScanDir struct {
	ScanDir *ScanDirectoryResponse `protobuf:"bytes,13,opt,name=scan_dir,json=scanDir,proto3,oneof"` // Response to scan a directory
}

func (*OperationResponse_ClaimUpdate) isOperationResponse_Response() {}

func (*OperationResponse_Mkdir) isOperationResponse_Response() {}

func (*OperationResponse_Lookup) isOperationResponse_Response() {}

func (*OperationResponse_GetAttr) isOperationResponse_Response() {}

func (*OperationResponse_Mknod) isOperationResponse_Response() {}

func (*OperationResponse_Rmdir) isOperationResponse_Response() {}

func (*OperationResponse_Unlink) isOperationResponse_Response() {}

func (*OperationResponse_Symlink) isOperationResponse_Response() {}

func (*OperationResponse_Readlink) isOperationResponse_Response() {}

func (*OperationResponse_SetAttr) isOperationResponse_Response() {}

func (*OperationResponse_ScanDir) isOperationResponse_Response() {}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the directory to create
	Stat          *FileStat              `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirRequest) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type MkdirResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the created directory.
	Cookie        []byte    `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Stat          *FileStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *MkdirResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *MkdirResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the file or directory to look up
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the looked-up file or directory.
	Cookie        []byte      `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Stat          *FileStat   `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`                          // Node information for the looked-up file or directory
	Claim         ClaimStatus `protobuf:"varint,3,opt,name=claim,proto3,enum=mtfs.ClaimStatus" json:"claim,omitempty"` // Claim status of the looked-up file or directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *LookupResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *LookupResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

func (x *LookupResponse) GetClaim() ClaimStatus {
	if x != nil {
		return x.Claim
	}
	return ClaimStatus_CLAIM_STATUS_UNSPECIFIED
}

type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

type GetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *FileStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"` // Statistics of the file or directory
	ClaimUpdate   ClaimStatus            `protobuf:"varint,2,opt,name=claim_update,json=claimUpdate,proto3,enum=mtfs.ClaimStatus" json:"claim_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrResponse) Reset() {
	*x = GetAttrResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrResponse) ProtoMessage() {}

func (x *GetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrResponse.ProtoReflect.Descriptor instead.
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttrResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

func (x *GetAttrResponse) GetClaimUpdate() ClaimStatus {
	if x != nil {
		return x.ClaimUpdate
	}
	return ClaimStatus_CLAIM_STATUS_UNSPECIFIED
}

type MknodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the node to create
	Stat          *FileStat              `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"` // Statistics for the node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MknodRequest) Reset() {
	*x = MknodRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MknodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MknodRequest) ProtoMessage() {}

func (x *MknodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MknodRequest.ProtoReflect.Descriptor instead.
func (*MknodRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *MknodRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MknodRequest) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type MknodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        []byte                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"` // Identifier of the created node
	Stat          *FileStat              `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`     // Statistics of the created node
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MknodResponse) Reset() {
	*x = MknodResponse{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MknodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MknodResponse) ProtoMessage() {}

func (x *MknodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MknodResponse.ProtoReflect.Descriptor instead.
func (*MknodResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *MknodResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *MknodResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type RmdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the directory to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirRequest) Reset() {
	*x = RmdirRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirRequest) ProtoMessage() {}

func (x *RmdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirRequest.ProtoReflect.Descriptor instead.
func (*RmdirRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *RmdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RmdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirResponse) Reset() {
	*x = RmdirResponse{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirResponse) ProtoMessage() {}

func (x *RmdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirResponse.ProtoReflect.Descriptor instead.
func (*RmdirResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

type UnlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the file to remove
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkRequest) Reset() {
	*x = UnlinkRequest{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRequest) ProtoMessage() {}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *UnlinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UnlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkResponse) Reset() {
	*x = UnlinkResponse{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkResponse) ProtoMessage() {}

func (x *UnlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkResponse.ProtoReflect.Descriptor instead.
func (*UnlinkResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

type SymlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`     // Name of the symlink to create
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"` // Target of the symlink
	Stat          *FileStat              `protobuf:"bytes,3,opt,name=stat,proto3" json:"stat,omitempty"`     // Statistics for the symlink
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymlinkRequest) Reset() {
	*x = SymlinkRequest{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkRequest) ProtoMessage() {}

func (x *SymlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkRequest.ProtoReflect.Descriptor instead.
func (*SymlinkRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *SymlinkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SymlinkRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SymlinkRequest) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type SymlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cookie        []byte                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"` // Identifier of the created symlink
	Stat          *FileStat              `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`     // Statistics of the created symlink
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymlinkResponse) Reset() {
	*x = SymlinkResponse{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkResponse) ProtoMessage() {}

func (x *SymlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkResponse.ProtoReflect.Descriptor instead.
func (*SymlinkResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *SymlinkResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *SymlinkResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type ReadlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadlinkRequest) Reset() {
	*x = ReadlinkRequest{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadlinkRequest) ProtoMessage() {}

func (x *ReadlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadlinkRequest.ProtoReflect.Descriptor instead.
func (*ReadlinkRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

type ReadlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        []byte                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // Target of the symlink
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadlinkResponse) Reset() {
	*x = ReadlinkResponse{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadlinkResponse) ProtoMessage() {}

func (x *ReadlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadlinkResponse.ProtoReflect.Descriptor instead.
func (*ReadlinkResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *ReadlinkResponse) GetTarget() []byte {
	if x != nil {
		return x.Target
	}
	return nil
}

type SetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *FileStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"` // New statistics for the file or directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttrRequest) Reset() {
	*x = SetAttrRequest{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttrRequest) ProtoMessage() {}

func (x *SetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttrRequest.ProtoReflect.Descriptor instead.
func (*SetAttrRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *SetAttrRequest) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type SetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *FileStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"` // Updated statistics of the file or directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAttrResponse) Reset() {
	*x = SetAttrResponse{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttrResponse) ProtoMessage() {}

func (x *SetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttrResponse.ProtoReflect.Descriptor instead.
func (*SetAttrResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *SetAttrResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type ScanDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // Token for the directory to scan. Empty for scan from the beginning.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanDirectoryRequest) Reset() {
	*x = ScanDirectoryRequest{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDirectoryRequest) ProtoMessage() {}

func (x *ScanDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ScanDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *ScanDirectoryRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type ScanDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`                            // List of directory entries
	OffsetToken   []byte                 `protobuf:"bytes,2,opt,name=offset_token,json=offsetToken,proto3" json:"offset_token,omitempty"` // Token for the next offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanDirectoryResponse) Reset() {
	*x = ScanDirectoryResponse{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanDirectoryResponse) ProtoMessage() {}

func (x *ScanDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ScanDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *ScanDirectoryResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ScanDirectoryResponse) GetOffsetToken() []byte {
	if x != nil {
		return x.OffsetToken
	}
	return nil
}

type ClaimUpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ClaimStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=mtfs.ClaimStatus" json:"status,omitempty"` // Status of the claim update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimUpdateServerRequest) Reset() {
	*x = ClaimUpdateServerRequest{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimUpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimUpdateServerRequest) ProtoMessage() {}

func (x *ClaimUpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimUpdateServerRequest.ProtoReflect.Descriptor instead.
func (*ClaimUpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *ClaimUpdateServerRequest) GetStatus() ClaimStatus {
	if x != nil {
		return x.Status
	}
	return ClaimStatus_CLAIM_STATUS_UNSPECIFIED
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x74, 0x66, 0x73, 0x1a, 0x0d, 0x64, 0x69, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x04, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6b, 0x64, 0x69,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4d,
	0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6d,
	0x6b, 0x64, 0x69, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x12, 0x31, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x67,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6b, 0x6e, 0x6f, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4d, 0x6b, 0x6e,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x6b, 0x6e,
	0x6f, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x72, 0x6d, 0x64, 0x69, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x52, 0x6d, 0x64, 0x69, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x72, 0x6d, 0x64, 0x69, 0x72, 0x12, 0x2d,
	0x0a, 0x06, 0x75, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x55, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x75, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x30, 0x0a,
	0x07, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x12,
	0x33, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x31, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x53, 0x65,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x73, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x37, 0x0a, 0x08, 0x73, 0x63, 0x61, 0x6e, 0x5f,
	0x64, 0x69, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x74, 0x66, 0x73,
	0x2e, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x73, 0x63, 0x61, 0x6e, 0x44, 0x69, 0x72,
	0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x85, 0x05,
	0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x6f, 0x6b, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b,
	0x69, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e,
	0x43, 0x6c, 0x61, 0x69, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x69,
	0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x6b, 0x64, 0x69, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4d, 0x6b,
	0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x6d,
	0x6b, 0x64, 0x69, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x07, 0x67, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x6b, 0x6e, 0x6f,
	0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4d,
	0x6b, 0x6e, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x6d, 0x6b, 0x6e, 0x6f, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x72, 0x6d, 0x64, 0x69, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x52, 0x6d, 0x64, 0x69,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05, 0x72, 0x6d, 0x64,
	0x69, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x75, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x55, 0x6e, 0x6c, 0x69, 0x6e, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x75, 0x6e, 0x6c, 0x69,
	0x6e, 0x6b, 0x12, 0x31, 0x0a, 0x07, 0x73, 0x79, 0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x53, 0x79, 0x6d, 0x6c, 0x69,
	0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x79,
	0x6d, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x34, 0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e,
	0x6b, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x32, 0x0a, 0x08, 0x73,
	0x65, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x6d, 0x74, 0x66, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x07, 0x73, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12,
	0x38, 0x0a, 0x08, 0x73, 0x63, 0x61, 0x6e, 0x5f, 0x64, 0x69, 0x72, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x73, 0x63, 0x61, 0x6e, 0x44, 0x69, 0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x4b, 0x0a,
	0x0d, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x23, 0x0a, 0x0d, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x75, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x12, 0x27, 0x0a,
	0x05, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d,
	0x74, 0x66, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x05, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73,
	0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x12,
	0x34, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x43, 0x6c, 0x61,
	0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x4d, 0x6b, 0x6e, 0x6f, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x4b, 0x0a,
	0x0d, 0x4d, 0x6b, 0x6e, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x6d,
	0x64, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x0f,
	0x0a, 0x0d, 0x52, 0x6d, 0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x23, 0x0a, 0x0d, 0x55, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x55, 0x6e, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x60, 0x0a, 0x0e, 0x53, 0x79, 0x6d, 0x6c, 0x69, 0x6e,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x4d, 0x0a, 0x0f, 0x53, 0x79, 0x6d, 0x6c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x6c,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x10, 0x52, 0x65,
	0x61, 0x64, 0x6c, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22, 0x35, 0x0a, 0x0f,
	0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73,
	0x74, 0x61, 0x74, 0x22, 0x2c, 0x0a, 0x14, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x64, 0x0a, 0x15, 0x53, 0x63, 0x61, 0x6e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74,
	0x66, 0x73, 0x2e, 0x44, 0x69, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x5f, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x45, 0x0a, 0x18, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0xc7,
	0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x18, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x28, 0x0a, 0x24,
	0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x43,
	0x4c, 0x55, 0x53, 0x49, 0x56, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x47, 0x52, 0x41,
	0x4e, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x41, 0x44,
	0x5f, 0x47, 0x52, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x28, 0x0a, 0x24, 0x43, 0x4c,
	0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x43, 0x4c, 0x55,
	0x53, 0x49, 0x56, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x56, 0x4f, 0x4b,
	0x45, 0x44, 0x10, 0x03, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x52,
	0x45, 0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x04, 0x32, 0x4d, 0x0a, 0x0b, 0x4d, 0x74, 0x66, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x12, 0x16, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x76, 0x65, 0x6c, 0x64, 0x61,
	0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_service_proto_goTypes = []any{
	(ClaimStatus)(0),                 // 0: mtfs.ClaimStatus
	(*OperationRequest)(nil),         // 1: mtfs.OperationRequest
	(*OperationResponse)(nil),        // 2: mtfs.OperationResponse
	(*MkdirRequest)(nil),             // 3: mtfs.MkdirRequest
	(*MkdirResponse)(nil),            // 4: mtfs.MkdirResponse
	(*LookupRequest)(nil),            // 5: mtfs.LookupRequest
	(*LookupResponse)(nil),           // 6: mtfs.LookupResponse
	(*GetAttrRequest)(nil),           // 7: mtfs.GetAttrRequest
	(*GetAttrResponse)(nil),          // 8: mtfs.GetAttrResponse
	(*MknodRequest)(nil),             // 9: mtfs.MknodRequest
	(*MknodResponse)(nil),            // 10: mtfs.MknodResponse
	(*RmdirRequest)(nil),             // 11: mtfs.RmdirRequest
	(*RmdirResponse)(nil),            // 12: mtfs.RmdirResponse
	(*UnlinkRequest)(nil),            // 13: mtfs.UnlinkRequest
	(*UnlinkResponse)(nil),           // 14: mtfs.UnlinkResponse
	(*SymlinkRequest)(nil),           // 15: mtfs.SymlinkRequest
	(*SymlinkResponse)(nil),          // 16: mtfs.SymlinkResponse
	(*ReadlinkRequest)(nil),          // 17: mtfs.ReadlinkRequest
	(*ReadlinkResponse)(nil),         // 18: mtfs.ReadlinkResponse
	(*SetAttrRequest)(nil),           // 19: mtfs.SetAttrRequest
	(*SetAttrResponse)(nil),          // 20: mtfs.SetAttrResponse
	(*ScanDirectoryRequest)(nil),     // 21: mtfs.ScanDirectoryRequest
	(*ScanDirectoryResponse)(nil),    // 22: mtfs.ScanDirectoryResponse
	(*ClaimUpdateServerRequest)(nil), // 23: mtfs.ClaimUpdateServerRequest
	(*FileStat)(nil),                 // 24: mtfs.FileStat
	(*DirEntry)(nil),                 // 25: mtfs.DirEntry
}
var file_service_proto_depIdxs = []int32{
	3,  // 0: mtfs.OperationRequest.mkdir:type_name -> mtfs.MkdirRequest
	5,  // 1: mtfs.OperationRequest.lookup:type_name -> mtfs.LookupRequest
	7,  // 2: mtfs.OperationRequest.get_attr:type_name -> mtfs.GetAttrRequest
	9,  // 3: mtfs.OperationRequest.mknod:type_name -> mtfs.MknodRequest
	11, // 4: mtfs.OperationRequest.rmdir:type_name -> mtfs.RmdirRequest
	13, // 5: mtfs.OperationRequest.unlink:type_name -> mtfs.UnlinkRequest
	15, // 6: mtfs.OperationRequest.symlink:type_name -> mtfs.SymlinkRequest
	17, // 7: mtfs.OperationRequest.readlink:type_name -> mtfs.ReadlinkRequest
	19, // 8: mtfs.OperationRequest.set_attr:type_name -> mtfs.SetAttrRequest
	21, // 9: mtfs.OperationRequest.scan_dir:type_name -> mtfs.ScanDirectoryRequest
	23, // 10: mtfs.OperationResponse.claim_update:type_name -> mtfs.ClaimUpdateServerRequest
	4,  // 11: mtfs.OperationResponse.mkdir:type_name -> mtfs.MkdirResponse
	6,  // 12: mtfs.OperationResponse.lookup:type_name -> mtfs.LookupResponse
	8,  // 13: mtfs.OperationResponse.get_attr:type_name -> mtfs.GetAttrResponse
	10, // 14: mtfs.OperationResponse.mknod:type_name -> mtfs.MknodResponse
	12, // 15: mtfs.OperationResponse.rmdir:type_name -> mtfs.RmdirResponse
	14, // 16: mtfs.OperationResponse.unlink:type_name -> mtfs.UnlinkResponse
	16, // 17: mtfs.OperationResponse.symlink:type_name -> mtfs.SymlinkResponse
	18, // 18: mtfs.OperationResponse.readlink:type_name -> mtfs.ReadlinkResponse
	20, // 19: mtfs.OperationResponse.set_attr:type_name -> mtfs.SetAttrResponse
	22, // 20: mtfs.OperationResponse.scan_dir:type_name -> mtfs.ScanDirectoryResponse
	24, // 21: mtfs.MkdirRequest.stat:type_name -> mtfs.FileStat
	24, // 22: mtfs.MkdirResponse.stat:type_name -> mtfs.FileStat
	24, // 23: mtfs.LookupResponse.stat:type_name -> mtfs.FileStat
	0,  // 24: mtfs.LookupResponse.claim:type_name -> mtfs.ClaimStatus
	24, // 25: mtfs.GetAttrResponse.stat:type_name -> mtfs.FileStat
	0,  // 26: mtfs.GetAttrResponse.claim_update:type_name -> mtfs.ClaimStatus
	24, // 27: mtfs.MknodRequest.stat:type_name -> mtfs.FileStat
	24, // 28: mtfs.MknodResponse.stat:type_name -> mtfs.FileStat
	24, // 29: mtfs.SymlinkRequest.stat:type_name -> mtfs.FileStat
	24, // 30: mtfs.SymlinkResponse.stat:type_name -> mtfs.FileStat
	24, // 31: mtfs.SetAttrRequest.stat:type_name -> mtfs.FileStat
	24, // 32: mtfs.SetAttrResponse.stat:type_name -> mtfs.FileStat
	25, // 33: mtfs.ScanDirectoryResponse.entries:type_name -> mtfs.DirEntry
	0,  // 34: mtfs.ClaimUpdateServerRequest.status:type_name -> mtfs.ClaimStatus
	1,  // 35: mtfs.MtfsService.Serve:input_type -> mtfs.OperationRequest
	2,  // 36: mtfs.MtfsService.Serve:output_type -> mtfs.OperationResponse
	36, // [36:37] is the sub-list for method output_type
	35, // [35:36] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_dirnode_proto_init()
	file_service_proto_msgTypes[0].OneofWrappers = []any{
		(*OperationRequest_Mkdir)(nil),
		(*OperationRequest_Lookup)(nil),
		(*OperationRequest_GetAttr)(nil),
		(*OperationRequest_Mknod)(nil),
		(*OperationRequest_Rmdir)(nil),
		(*OperationRequest_Unlink)(nil),
		(*OperationRequest_Symlink)(nil),
		(*OperationRequest_Readlink)(nil),
		(*OperationRequest_SetAttr)(nil),
		(*OperationRequest_ScanDir)(nil),
	}
	file_service_proto_msgTypes[1].OneofWrappers = []any{
		(*OperationResponse_ClaimUpdate)(nil),
		(*OperationResponse_Mkdir)(nil),
		(*OperationResponse_Lookup)(nil),
		(*OperationResponse_GetAttr)(nil),
		(*OperationResponse_Mknod)(nil),
		(*OperationResponse_Rmdir)(nil),
		(*OperationResponse_Unlink)(nil),
		(*OperationResponse_Symlink)(nil),
		(*OperationResponse_Readlink)(nil),
		(*OperationResponse_SetAttr)(nil),
		(*OperationResponse_ScanDir)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
