// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClfsService_Serve_FullMethodName = "/clfs.ClfsService/Serve"
)

// ClfsServiceClient is the client API for ClfsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClfsServiceClient interface {
	// Creates a working connection to the CLFS service.
	Serve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OperationRequest, OperationResponse], error)
}

type clfsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClfsServiceClient(cc grpc.ClientConnInterface) ClfsServiceClient {
	return &clfsServiceClient{cc}
}

func (c *clfsServiceClient) Serve(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[OperationRequest, OperationResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClfsService_ServiceDesc.Streams[0], ClfsService_Serve_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[OperationRequest, OperationResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClfsService_ServeClient = grpc.BidiStreamingClient[OperationRequest, OperationResponse]

// ClfsServiceServer is the server API for ClfsService service.
// All implementations must embed UnimplementedClfsServiceServer
// for forward compatibility.
type ClfsServiceServer interface {
	// Creates a working connection to the CLFS service.
	Serve(grpc.BidiStreamingServer[OperationRequest, OperationResponse]) error
	mustEmbedUnimplementedClfsServiceServer()
}

// UnimplementedClfsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClfsServiceServer struct{}

func (UnimplementedClfsServiceServer) Serve(grpc.BidiStreamingServer[OperationRequest, OperationResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Serve not implemented")
}
func (UnimplementedClfsServiceServer) mustEmbedUnimplementedClfsServiceServer() {}
func (UnimplementedClfsServiceServer) testEmbeddedByValue()                     {}

// UnsafeClfsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClfsServiceServer will
// result in compilation errors.
type UnsafeClfsServiceServer interface {
	mustEmbedUnimplementedClfsServiceServer()
}

func RegisterClfsServiceServer(s grpc.ServiceRegistrar, srv ClfsServiceServer) {
	// If the following call pancis, it indicates UnimplementedClfsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClfsService_ServiceDesc, srv)
}

func _ClfsService_Serve_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClfsServiceServer).Serve(&grpc.GenericServerStream[OperationRequest, OperationResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClfsService_ServeServer = grpc.BidiStreamingServer[OperationRequest, OperationResponse]

// ClfsService_ServiceDesc is the grpc.ServiceDesc for ClfsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClfsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clfs.ClfsService",
	HandlerType: (*ClfsServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Serve",
			Handler:       _ClfsService_Serve_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
