// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v3.21.12
// source: service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClaimStatus int32

const (
	ClaimStatus_CLAIM_STATUS_UNSPECIFIED             ClaimStatus = 0 // Unspecified claim status
	ClaimStatus_CLAIM_STATUS_EXCLUSIVE_WRITE_GRANTED ClaimStatus = 1 // Exclusive write access granted
	ClaimStatus_CLAIM_STATUS_LOCK_READ_GRANTED       ClaimStatus = 2 // Read lock granted
	ClaimStatus_CLAIM_STATUS_EXCLUSIVE_WRITE_REVOKED ClaimStatus = 3 // Write lock revoked
	ClaimStatus_CLAIM_STATUS_LOCK_READ_REVOKED       ClaimStatus = 4 // Read lock revoked
)

// Enum value maps for ClaimStatus.
var (
	ClaimStatus_name = map[int32]string{
		0: "CLAIM_STATUS_UNSPECIFIED",
		1: "CLAIM_STATUS_EXCLUSIVE_WRITE_GRANTED",
		2: "CLAIM_STATUS_LOCK_READ_GRANTED",
		3: "CLAIM_STATUS_EXCLUSIVE_WRITE_REVOKED",
		4: "CLAIM_STATUS_LOCK_READ_REVOKED",
	}
	ClaimStatus_value = map[string]int32{
		"CLAIM_STATUS_UNSPECIFIED":             0,
		"CLAIM_STATUS_EXCLUSIVE_WRITE_GRANTED": 1,
		"CLAIM_STATUS_LOCK_READ_GRANTED":       2,
		"CLAIM_STATUS_EXCLUSIVE_WRITE_REVOKED": 3,
		"CLAIM_STATUS_LOCK_READ_REVOKED":       4,
	}
)

func (x ClaimStatus) Enum() *ClaimStatus {
	p := new(ClaimStatus)
	*p = x
	return p
}

func (x ClaimStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClaimStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (ClaimStatus) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x ClaimStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClaimStatus.Descriptor instead.
func (ClaimStatus) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type OperationRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Cookie []byte                 `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`             // Cookie for the request
	SeqId  int64                  `protobuf:"varint,2,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"` // Sequence ID of the request
	// Types that are valid to be assigned to Operation:
	//
	//	*OperationRequest_Mkdir
	//	*OperationRequest_Lookup
	//	*OperationRequest_GetAttr
	Operation     isOperationRequest_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *OperationRequest) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *OperationRequest) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *OperationRequest) GetOperation() isOperationRequest_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *OperationRequest) GetMkdir() *MkdirRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *OperationRequest) GetLookup() *LookupRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

func (x *OperationRequest) GetGetAttr() *GetAttrRequest {
	if x != nil {
		if x, ok := x.Operation.(*OperationRequest_GetAttr); ok {
			return x.GetAttr
		}
	}
	return nil
}

type isOperationRequest_Operation interface {
	isOperationRequest_Operation()
}

type OperationRequest_Mkdir struct {
	// Request to create a directory.
	Mkdir *MkdirRequest `protobuf:"bytes,3,opt,name=mkdir,proto3,oneof"`
}

type OperationRequest_Lookup struct {
	Lookup *LookupRequest `protobuf:"bytes,4,opt,name=lookup,proto3,oneof"` // Request to look up a file or directory
}

type OperationRequest_GetAttr struct {
	GetAttr *GetAttrRequest `protobuf:"bytes,5,opt,name=get_attr,json=getAttr,proto3,oneof"` // Request to get file or directory attributes
}

func (*OperationRequest_Mkdir) isOperationRequest_Operation() {}

func (*OperationRequest_Lookup) isOperationRequest_Operation() {}

func (*OperationRequest_GetAttr) isOperationRequest_Operation() {}

type OperationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sequence ID of the request, 0 if it's notification from the server
	SeqId  int64  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Cookie []byte `protobuf:"bytes,2,opt,name=cookie,proto3" json:"cookie,omitempty"` // Cookie for the identity of the inode.
	// Types that are valid to be assigned to Response:
	//
	//	*OperationResponse_Mkdir
	//	*OperationResponse_Lookup
	//	*OperationResponse_GetAttr
	//	*OperationResponse_ClaimUpdate
	Response      isOperationResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *OperationResponse) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *OperationResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *OperationResponse) GetResponse() isOperationResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *OperationResponse) GetMkdir() *MkdirResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *OperationResponse) GetLookup() *LookupResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_Lookup); ok {
			return x.Lookup
		}
	}
	return nil
}

func (x *OperationResponse) GetGetAttr() *GetAttrResponse {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_GetAttr); ok {
			return x.GetAttr
		}
	}
	return nil
}

func (x *OperationResponse) GetClaimUpdate() *ClaimUpdateServerRequest {
	if x != nil {
		if x, ok := x.Response.(*OperationResponse_ClaimUpdate); ok {
			return x.ClaimUpdate
		}
	}
	return nil
}

type isOperationResponse_Response interface {
	isOperationResponse_Response()
}

type OperationResponse_Mkdir struct {
	// Response to a directory creation request.
	Mkdir *MkdirResponse `protobuf:"bytes,3,opt,name=mkdir,proto3,oneof"`
}

type OperationResponse_Lookup struct {
	Lookup *LookupResponse `protobuf:"bytes,4,opt,name=lookup,proto3,oneof"` // Response to a lookup request
}

type OperationResponse_GetAttr struct {
	GetAttr *GetAttrResponse `protobuf:"bytes,5,opt,name=get_attr,json=getAttr,proto3,oneof"` // Response to a stat request
}

type OperationResponse_ClaimUpdate struct {
	// Belows are notifications from the server.
	ClaimUpdate *ClaimUpdateServerRequest `protobuf:"bytes,6,opt,name=claim_update,json=claimUpdate,proto3,oneof"` // Claim update request
}

func (*OperationResponse_Mkdir) isOperationResponse_Response() {}

func (*OperationResponse_Lookup) isOperationResponse_Response() {}

func (*OperationResponse_GetAttr) isOperationResponse_Response() {}

func (*OperationResponse_ClaimUpdate) isOperationResponse_Response() {}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the directory to create
	Stat          *FileStat              `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *MkdirRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MkdirRequest) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type MkdirResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the created directory.
	Cookie        []byte    `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Stat          *FileStat `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *MkdirResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *MkdirResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Name of the file or directory to look up
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the looked-up file or directory.
	Cookie        []byte      `protobuf:"bytes,1,opt,name=cookie,proto3" json:"cookie,omitempty"`
	Stat          *FileStat   `protobuf:"bytes,2,opt,name=stat,proto3" json:"stat,omitempty"`                          // Node information for the looked-up file or directory
	Claim         ClaimStatus `protobuf:"varint,3,opt,name=claim,proto3,enum=mtfs.ClaimStatus" json:"claim,omitempty"` // Claim status of the looked-up file or directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *LookupResponse) GetCookie() []byte {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *LookupResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

func (x *LookupResponse) GetClaim() ClaimStatus {
	if x != nil {
		return x.Claim
	}
	return ClaimStatus_CLAIM_STATUS_UNSPECIFIED
}

type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

type GetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          *FileStat              `protobuf:"bytes,1,opt,name=stat,proto3" json:"stat,omitempty"` // Statistics of the file or directory
	ClaimUpdate   ClaimStatus            `protobuf:"varint,2,opt,name=claim_update,json=claimUpdate,proto3,enum=mtfs.ClaimStatus" json:"claim_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrResponse) Reset() {
	*x = GetAttrResponse{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrResponse) ProtoMessage() {}

func (x *GetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrResponse.ProtoReflect.Descriptor instead.
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttrResponse) GetStat() *FileStat {
	if x != nil {
		return x.Stat
	}
	return nil
}

func (x *GetAttrResponse) GetClaimUpdate() ClaimStatus {
	if x != nil {
		return x.ClaimUpdate
	}
	return ClaimStatus_CLAIM_STATUS_UNSPECIFIED
}

type ClaimUpdateServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ClaimStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=mtfs.ClaimStatus" json:"status,omitempty"` // Status of the claim update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimUpdateServerRequest) Reset() {
	*x = ClaimUpdateServerRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimUpdateServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimUpdateServerRequest) ProtoMessage() {}

func (x *ClaimUpdateServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimUpdateServerRequest.ProtoReflect.Descriptor instead.
func (*ClaimUpdateServerRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *ClaimUpdateServerRequest) GetStatus() ClaimStatus {
	if x != nil {
		return x.Status
	}
	return ClaimStatus_CLAIM_STATUS_UNSPECIFIED
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x6d, 0x74, 0x66, 0x73, 0x1a, 0x0d, 0x64, 0x69, 0x72, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdc, 0x01, 0x0a, 0x10, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69,
	0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x6b, 0x64, 0x69,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4d,
	0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x05, 0x6d,
	0x6b, 0x64, 0x69, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x6c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x12, 0x31, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x07, 0x67,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x42, 0x0b, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xa4, 0x02, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x73, 0x65, 0x71,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x6d, 0x6b, 0x64, 0x69,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4d,
	0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x05,
	0x6d, 0x6b, 0x64, 0x69, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4c, 0x6f, 0x6f,
	0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x06, 0x6c,
	0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x32, 0x0a, 0x08, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x74, 0x74,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x07, 0x67, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x12, 0x43, 0x0a, 0x0c, 0x63, 0x6c, 0x61,
	0x69, 0x6d, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x0a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x0c, 0x4d, 0x6b,
	0x64, 0x69, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x22,
	0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74,
	0x61, 0x74, 0x22, 0x4b, 0x0a, 0x0d, 0x4d, 0x6b, 0x64, 0x69, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x73,
	0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x66, 0x73,
	0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74, 0x61, 0x74, 0x22,
	0x23, 0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x12, 0x22,
	0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04, 0x73, 0x74,
	0x61, 0x74, 0x12, 0x27, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x22, 0x10, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x41, 0x74, 0x74, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x22, 0x0a, 0x04, 0x73, 0x74, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x52, 0x04,
	0x73, 0x74, 0x61, 0x74, 0x12, 0x34, 0x0a, 0x0c, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x74, 0x66,
	0x73, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0b, 0x63,
	0x6c, 0x61, 0x69, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x45, 0x0a, 0x18, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x43, 0x6c,
	0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2a, 0xc7, 0x01, 0x0a, 0x0b, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1c, 0x0a, 0x18, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x28, 0x0a, 0x24, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x45, 0x58, 0x43, 0x4c, 0x55, 0x53, 0x49, 0x56, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f,
	0x47, 0x52, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4c, 0x41,
	0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x5f, 0x47, 0x52, 0x41, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x28, 0x0a,
	0x24, 0x43, 0x4c, 0x41, 0x49, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58,
	0x43, 0x4c, 0x55, 0x53, 0x49, 0x56, 0x45, 0x5f, 0x57, 0x52, 0x49, 0x54, 0x45, 0x5f, 0x52, 0x45,
	0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x03, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4c, 0x41, 0x49, 0x4d,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4c, 0x4f, 0x43, 0x4b, 0x5f, 0x52, 0x45, 0x41,
	0x44, 0x5f, 0x52, 0x45, 0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x04, 0x32, 0x4d, 0x0a, 0x0b, 0x4d,
	0x74, 0x66, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x05, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x6d, 0x74, 0x66, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x74,
	0x66, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x19, 0x5a, 0x17, 0x76, 0x65,
	0x6c, 0x64, 0x61, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x74, 0x66, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_proto_goTypes = []any{
	(ClaimStatus)(0),                 // 0: mtfs.ClaimStatus
	(*OperationRequest)(nil),         // 1: mtfs.OperationRequest
	(*OperationResponse)(nil),        // 2: mtfs.OperationResponse
	(*MkdirRequest)(nil),             // 3: mtfs.MkdirRequest
	(*MkdirResponse)(nil),            // 4: mtfs.MkdirResponse
	(*LookupRequest)(nil),            // 5: mtfs.LookupRequest
	(*LookupResponse)(nil),           // 6: mtfs.LookupResponse
	(*GetAttrRequest)(nil),           // 7: mtfs.GetAttrRequest
	(*GetAttrResponse)(nil),          // 8: mtfs.GetAttrResponse
	(*ClaimUpdateServerRequest)(nil), // 9: mtfs.ClaimUpdateServerRequest
	(*FileStat)(nil),                 // 10: mtfs.FileStat
}
var file_service_proto_depIdxs = []int32{
	3,  // 0: mtfs.OperationRequest.mkdir:type_name -> mtfs.MkdirRequest
	5,  // 1: mtfs.OperationRequest.lookup:type_name -> mtfs.LookupRequest
	7,  // 2: mtfs.OperationRequest.get_attr:type_name -> mtfs.GetAttrRequest
	4,  // 3: mtfs.OperationResponse.mkdir:type_name -> mtfs.MkdirResponse
	6,  // 4: mtfs.OperationResponse.lookup:type_name -> mtfs.LookupResponse
	8,  // 5: mtfs.OperationResponse.get_attr:type_name -> mtfs.GetAttrResponse
	9,  // 6: mtfs.OperationResponse.claim_update:type_name -> mtfs.ClaimUpdateServerRequest
	10, // 7: mtfs.MkdirRequest.stat:type_name -> mtfs.FileStat
	10, // 8: mtfs.MkdirResponse.stat:type_name -> mtfs.FileStat
	10, // 9: mtfs.LookupResponse.stat:type_name -> mtfs.FileStat
	0,  // 10: mtfs.LookupResponse.claim:type_name -> mtfs.ClaimStatus
	10, // 11: mtfs.GetAttrResponse.stat:type_name -> mtfs.FileStat
	0,  // 12: mtfs.GetAttrResponse.claim_update:type_name -> mtfs.ClaimStatus
	0,  // 13: mtfs.ClaimUpdateServerRequest.status:type_name -> mtfs.ClaimStatus
	1,  // 14: mtfs.MtfsService.Serve:input_type -> mtfs.OperationRequest
	2,  // 15: mtfs.MtfsService.Serve:output_type -> mtfs.OperationResponse
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_dirnode_proto_init()
	file_service_proto_msgTypes[0].OneofWrappers = []any{
		(*OperationRequest_Mkdir)(nil),
		(*OperationRequest_Lookup)(nil),
		(*OperationRequest_GetAttr)(nil),
	}
	file_service_proto_msgTypes[1].OneofWrappers = []any{
		(*OperationResponse_Mkdir)(nil),
		(*OperationResponse_Lookup)(nil),
		(*OperationResponse_GetAttr)(nil),
		(*OperationResponse_ClaimUpdate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
